# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: greating_service.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x16greating_service.proto\x12\x10\x63om.example.grpc\"(\n\x07Request\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\x0f\n\x07hobbies\x18\x02 \x03(\t\"\x1c\n\x08Response\x12\x10\n\x08greeting\x18\x01 \x01(\t2R\n\rSimpleService\x12\x41\n\x08greeting\x12\x19.com.example.grpc.Request\x1a\x1a.com.example.grpc.Responseb\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'greating_service_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _REQUEST._serialized_start=44
  _REQUEST._serialized_end=84
  _RESPONSE._serialized_start=86
  _RESPONSE._serialized_end=114
  _SIMPLESERVICE._serialized_start=116
  _SIMPLESERVICE._serialized_end=198
# @@protoc_insertion_point(module_scope)
